<div class="legal-page">
    <div class="legal-content">
        <h1>Privacy Policy</h1>
        <p class="legal-updated">Last updated: 27 February 2026</p>

        <section>
            <h2>1. Who we are</h2>
            <p>
                Woof is a social network for dogs and their owners. The service is operated
                by Tommi Kivisaari ("we", "us", "Woof"). For privacy-related inquiries,
                contact us at <a href="mailto:privacy@woofapp.fi">privacy@woofapp.fi</a>.
            </p>
        </section>

        <section>
            <h2>2. What data we collect</h2>
            <ul>
                <li><strong>Account data:</strong> your email address and display name, provided when you register.</li>
                <li><strong>Dog profiles:</strong> name, breed, birth date, location, bio, and profile photos you add.</li>
                <li><strong>Uploaded photos:</strong> images you post to the feed.</li>
                <li><strong>Usage data:</strong> posts, likes, comments, follows, messages, and notifications generated by your activity.</li>
                <li><strong>Technical data:</strong> session tokens stored in your browser's <code>localStorage</code> (not cookies). No tracking cookies are used.</li>
            </ul>
        </section>

        <section>
            <h2>3. Legal basis for processing</h2>
            <ul>
                <li><strong>Contract (GDPR Art. 6(1)(b)):</strong> processing your account data and content is necessary to provide the service you signed up for.</li>
                <li><strong>Legitimate interest (GDPR Art. 6(1)(f)):</strong> automated image moderation to protect users from harmful content.</li>
            </ul>
        </section>

        <section>
            <h2>4. Third-party processors</h2>
            <p>All processing takes place within the European Union (AWS eu-north-1, Stockholm).</p>
            <ul>
                <li>
                    <strong>Amazon Web Services (AWS):</strong> hosting (Elastic Beanstalk), database (RDS PostgreSQL),
                    image storage (S3), content delivery (CloudFront), and user authentication (Cognito).
                    All data stays in the EU.
                </li>
                <li>
                    <strong>Amazon Rekognition:</strong> automated image moderation. When you upload a photo,
                    it is analysed by Rekognition within AWS eu-north-1 to detect potentially harmful content.
                    No image data leaves the EU.
                </li>
            </ul>
        </section>

        <section>
            <h2>5. Data retention</h2>
            <ul>
                <li>Account data and content: retained until you delete your account.</li>
                <li>Server logs: up to 90 days.</li>
            </ul>
            <p>
                You can delete your account at any time from your profile settings.
                Deletion removes all your personal data, dogs, posts, comments, and messages.
            </p>
        </section>

        <section>
            <h2>6. Your rights</h2>
            <p>Under GDPR you have the right to:</p>
            <ul>
                <li><strong>Access</strong> the personal data we hold about you.</li>
                <li><strong>Rectify</strong> inaccurate data.</li>
                <li><strong>Erase</strong> your data ("right to be forgotten") — use the account deletion feature or contact us.</li>
                <li><strong>Data portability</strong> — request a copy of your data in a machine-readable format.</li>
                <li><strong>Object</strong> to processing based on legitimate interest.</li>
                <li><strong>Lodge a complaint</strong> with the Finnish Data Protection Ombudsman (Tietosuojavaltuutettu) at
                    <a href="https://tietosuoja.fi" target="_blank" rel="noopener noreferrer">tietosuoja.fi</a>.
                </li>
            </ul>
            <p>To exercise your rights, contact us at <a href="mailto:privacy@woofapp.fi">privacy@woofapp.fi</a>.</p>
        </section>

        <section>
            <h2>7. Cookies and local storage</h2>
            <p>
                Woof does not use tracking cookies. Your login session token is stored in your
                browser's <code>localStorage</code>. This is technically necessary to keep you
                logged in and is not used for advertising or analytics.
            </p>
        </section>

        <section>
            <h2>8. Contact</h2>
            <p>
                For any questions about this privacy policy or your personal data,
                contact us at <a href="mailto:privacy@woofapp.fi">privacy@woofapp.fi</a>.
            </p>
        </section>
    </div>
</div>

<style>
.legal-page {
    max-width: 680px;
    margin: 0 auto;
    padding: var(--woof-space-8) var(--woof-space-4) var(--woof-space-16);
}

.legal-content h1 {
    font-size: var(--woof-text-title-1);
    font-weight: var(--woof-font-weight-bold);
    color: var(--woof-color-neutral-900);
    margin-bottom: var(--woof-space-2);
}

.legal-updated {
    font-size: var(--woof-text-footnote);
    color: var(--woof-color-neutral-400);
    margin-bottom: var(--woof-space-8);
}

.legal-content section {
    margin-bottom: var(--woof-space-8);
}

.legal-content h2 {
    font-size: var(--woof-text-title-3);
    font-weight: var(--woof-font-weight-semibold);
    color: var(--woof-color-neutral-800);
    margin-bottom: var(--woof-space-3);
}

.legal-content p,
.legal-content li {
    font-size: var(--woof-text-body);
    color: var(--woof-color-neutral-700);
    line-height: 1.65;
}

.legal-content ul {
    padding-left: var(--woof-space-5);
    margin: var(--woof-space-3) 0;
}

.legal-content li {
    margin-bottom: var(--woof-space-2);
}

.legal-content a {
    color: var(--woof-color-brand-primary);
    text-decoration: none;
}

.legal-content a:hover {
    text-decoration: underline;
}

.legal-content code {
    font-family: monospace;
    background: var(--woof-color-neutral-100);
    padding: 1px 4px;
    border-radius: var(--woof-radius-sm);
    font-size: 0.9em;
}
</style>
